---
- name: Wait for port 22 to become open
  hosts: aws_ec2
  tasks:
    - name: ensure port 22 is open
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
        timeout: 100
  vars:
    ansible_connection: local
 
- name: Install Docker
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Install Docker
      vars:
        ansible_python_interpreter: /usr/bin/python3
      yum: 
        name: docker
        update_cache: yes
        state: present
    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-{{lookup('pipe','uname -s')}}-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Docker Deamon
      systemd:
        name: docker
        state: started
    - name: install pip3
      yum: 
        name: python3-pip
        update_cache: yes
        state: present
    - name: Uninstall requests
    # requests intalled via rpm cannot be unninstalled by pip
      yum: 
        name: python-requests
        state: absent
    - name: Install Python Docker Module ()
    # installing requests 2.28.1 because 2.29.x is giving errors (https://github.com/docker/docker-py/issues/3113)
      pip:
        name: 
          - docker
          - docker-compose
          - requests==2.26.0

- name: Add ec2-user to docker group
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Add ec2-user
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server
      meta: reset_connection

- name: Start docker container
  hosts: aws_ec2
  vars_files:
    - project-vars
  tasks:
    - name: copy docker-compose file
      copy:
        src: "{{docker_compose_path}}"
        dest: /home/ec2-user/docker-compose.yaml
    - name: docker login
      vars:
        ansible_python_interpreter: /usr/bin/python3
      docker_login: 
        registry_url: https://index.docker.io/v1/
        username: anrkuist
        password: "{{docker_password}}"
    - name: start container docker compose
      docker_compose:
        project_src: /home/ec2-user